In [13]:
import pandas as pd


def yesNo(x):
    if x=="YES":
        return 1
    else:
        return 0
    
def toOrd(str):
    x=0
    for l in str:
        x += ord(l)
    return int(x)

cols = ['User country', 'Nr. reviews','Nr. hotel reviews','Helpful votes',
        'Score','Period of stay','Traveler type','Pool','Gym','Tennis court',
        'Spa','Casino','Free internet','Hotel name','Hotel stars','Nr. rooms',
        'User continent','Member years','Review month','Review weekday']


df = pd.read_csv('/home/walker/TripAdvisor.csv',sep=',',header=0)

,User country,Nr. reviews,Nr. hotel reviews,Helpful votes,Score,Period of stay,Traveler type,Pool,Gym,Tennis court,Spa,Casino,Free internet,Hotel name,Hotel stars,Nr. rooms,User continent,Member years,Review month,Review weekday
0,USA,11,4,13,5,Dec-Feb,Friends,NO,YES,NO,NO,YES,YES,Circus Circus Hotel & Casino Las Vegas,3,3773,North America,9,January,Thursday
1,USA,119,21,75,3,Dec-Feb,Business,NO,YES,NO,NO,YES,YES,Circus Circus Hotel & Casino Las Vegas,3,3773,North America,3,January,Friday
2,USA,36,9,25,5,Mar-May,Families,NO,YES,NO,NO,YES,YES,Circus Circus Hotel & Casino Las Vegas,3,3773,North America,2,February,Saturday
3,UK,14,7,14,4,Mar-May,Friends,NO,YES,NO,NO,YES,YES,Circus Circus Hotel & Casino Las Vegas,3,3773,Europe,6,February,Friday
4,Canada,5,5,2,4,Mar-May,Solo,NO,YES,NO,NO,YES,YES,Circus Circus Hotel & Casino Las Vegas,3,3773,North America,7,March,Tuesday
5,Canada,31,8,27,3,Mar-May,Couples,NO,YES,NO,NO,YES,YES,Circus Circus Hotel & Casino Las Vegas,3,3773,North America,2,March,Tuesday
6,UK,45,12,46,4,Mar-May,Couples,NO,YES,NO,NO,YES,YES,Circus Circus Hotel & Casino Las Vegas,3,3773,Europe,4,April,Friday
7,USA,2,1,4,4,Mar-May,Families,NO,YES,NO,NO,YES,YES,Circus Circus Hotel & Casino Las Vegas,3,3773,North America,0,April,Tuesday
8,India,24,3,8,4,Mar-May,Friends,NO,YES,NO,NO,YES,YES,Circus Circus Hotel & Casino Las Vegas,3,3773,Asia,3,May,Saturday
9,Canada,12,7,11,3,Mar-May,Families,NO,YES,NO,NO,YES,YES,Circus Circus Hotel & Casino Las Vegas,3,3773,North America,5,May,Tuesday
10,USA,102,24,58,2,Jun-Aug,Families,NO,YES,NO,NO,YES,YES,Circus Circus Hotel & Casino Las Vegas,3,3773,North America,9,June,Friday
11,Australia,20,9,24,3,Jun-Aug,Friends,NO,YES,NO,NO,YES,YES,Circus Circus Hotel & Casino Las Vegas,3,3773,Oceania,4,June,Saturday
12,USA,7,6,9,2,Jun-Aug,Friends,NO,YES,NO,NO,YES,YES,Circus Circus Hotel & Casino Las Vegas,3,3773,North America,1,July,Wednesday
13,USA,22,5,13,3,Jun-Aug,Friends,NO,YES,NO,NO,YES,YES,Circus Circus Hotel & Casino Las Vegas,3,3773,North America,1,July,Thursday
14,UK,3,3,0,3,Jun-Aug,Friends,NO,YES,NO,NO,YES,YES,Circus Circus Hotel & Casino Las Vegas,3,3773,Europe,1,August,Sunday
15,New Zeland,146,17,33,4,Jun-Aug,Families,NO,YES,NO,NO,YES,YES,Circus Circus Hotel & Casino Las Vegas,3,3773,Oceania,2,August,Saturday
16,Canada,8,8,9,1,Sep-Nov,Families,NO,YES,NO,NO,YES,YES,Circus Circus Hotel & Casino Las Vegas,3,3773,North America,4,September,Wednesday
17,USA,9,3,1,4,Sep-Nov,Families,NO,YES,NO,NO,YES,YES,Circus Circus Hotel & Casino Las Vegas,3,3773,North America,2,September,Saturday
18,Canada,41,9,19,3,Sep-Nov,Couples,NO,YES,NO,NO,YES,YES,Circus Circus Hotel & Casino Las Vegas,3,3773,North America,2,October,Tuesday
19,USA,8,7,26,2,Sep-Nov,Couples,NO,YES,NO,NO,YES,YES,Circus Circus Hotel & Casino Las Vegas,3,3773,North America,10,October,Monday
20,UK,10,5,2,4,Sep-Nov,Couples,NO,YES,NO,NO,YES,YES,Circus Circus Hotel & Casino Las Vegas,3,3773,Europe,7,November,Saturday
21,New Zeland,4,3,3,1,Sep-Nov,Couples,NO,YES,NO,NO,YES,YES,Circus Circus Hotel & Casino Las Vegas,3,3773,Oceania,3,November,Monday
22,UK,18,7,19,4,Dec-Feb,Families,NO,YES,NO,NO,YES,YES,Circus Circus Hotel & Casino Las Vegas,3,3773,Europe,0,December,Saturday
23,USA,4,4,3,2,Dec-Feb,Couples,NO,YES,NO,NO,YES,YES,Circus Circus Hotel & Casino Las Vegas,3,3773,North America,5,December,Sunday
24,Ireland,29,11,15,4,Dec-Feb,Couples,YES,YES,NO,YES,YES,YES,Excalibur Hotel & Casino,3,3981,Europe,3,January,Monday
25,USA,114,42,52,4,Dec-Feb,Business,YES,YES,NO,YES,YES,YES,Excalibur Hotel & Casino,3,3981,North America,11,January,Saturday
26,Canada,30,12,17,5,Dec-Feb,Couples,YES,YES,NO,YES,YES,YES,Excalibur Hotel & Casino,3,3981,North America,8,February,Friday
27,UK,87,18,36,3,Dec-Feb,Business,YES,YES,NO,YES,YES,YES,Excalibur Hotel & Casino,3,3981,Europe,3,February,Thursday
28,USA,26,10,28,5,Mar-May,Solo,YES,YES,NO,YES,YES,YES,Excalibur Hotel & Casino,3,3981,North America,1,March,Wednesday
29,Ireland,8,7,9,5,Mar-May,Couples,YES,YES,NO,YES,YES,YES,Excalibur Hotel & Casino,3,3981,Europe,8,March,Wednesday
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
474,Canada,18,3,10,2,Sep-Nov,Couples,YES,YES,NO,YES,YES,YES,Paris Las Vegas,4,2916,North America,2,October,Monday
475,USA,6,4,6,5,Sep-Nov,Couples,YES,YES,NO,YES,YES,YES,Paris Las Vegas,4,2916,North America,0,October,Saturday
476,USA,48,8,25,4,Sep-Nov,Couples,YES,YES,NO,YES,YES,YES,Paris Las Vegas,4,2916,North America,6,November,Monday
477,USA,24,3,5,5,Sep-Nov,Couples,YES,YES,NO,YES,YES,YES,Paris Las Vegas,4,2916,North America,0,November,Sunday
478,Canada,123,26,63,5,Dec-Feb,Couples,YES,YES,NO,YES,YES,YES,Paris Las Vegas,4,2916,North America,4,December,Saturday
479,USA,24,7,6,4,Dec-Feb,Friends,YES,YES,NO,YES,YES,YES,Paris Las Vegas,4,2916,North America,1,December,Thursday
480,Canada,20,13,17,4,Dec-Feb,Couples,YES,YES,NO,YES,YES,YES,The Westin las Vegas Hotel Casino & Spa,4,826,North America,4,January,Monday
481,USA,15,3,4,3,Dec-Feb,Families,YES,YES,NO,YES,YES,YES,The Westin las Vegas Hotel Casino & Spa,4,826,North America,7,January,Tuesday
482,Italy,189,72,129,4,Dec-Feb,Solo,YES,YES,NO,YES,YES,YES,The Westin las Vegas Hotel Casino & Spa,4,826,Europe,3,February,Friday
483,USA,25,19,27,3,Dec-Feb,Couples,YES,YES,NO,YES,YES,YES,The Westin las Vegas Hotel Casino & Spa,4,826,North America,8,February,Monday
484,USA,33,11,12,5,Mar-May,Business,YES,YES,NO,YES,YES,YES,The Westin las Vegas Hotel Casino & Spa,4,826,North America,4,March,Wednesday
485,USA,14,7,13,5,Mar-May,Friends,YES,YES,NO,YES,YES,YES,The Westin las Vegas Hotel Casino & Spa,4,826,North America,4,March,Thursday
486,USA,38,22,47,4,Mar-May,Business,YES,YES,NO,YES,YES,YES,The Westin las Vegas Hotel Casino & Spa,4,826,North America,4,April,Monday
487,Egypt,169,43,85,4,Mar-May,Solo,YES,YES,NO,YES,YES,YES,The Westin las Vegas Hotel Casino & Spa,4,826,Africa,12,April,Sunday
488,USA,20,17,21,3,Mar-May,Friends,YES,YES,NO,YES,YES,YES,The Westin las Vegas Hotel Casino & Spa,4,826,North America,4,May,Sunday
489,USA,17,10,18,4,Mar-May,Couples,YES,YES,NO,YES,YES,YES,The Westin las Vegas Hotel Casino & Spa,4,826,North America,3,May,Tuesday
490,USA,96,47,161,4,Jun-Aug,Solo,YES,YES,NO,YES,YES,YES,The Westin las Vegas Hotel Casino & Spa,4,826,North America,11,June,Monday
491,USA,38,13,11,3,Jun-Aug,Business,YES,YES,NO,YES,YES,YES,The Westin las Vegas Hotel Casino & Spa,4,826,North America,5,June,Sunday
492,India,12,11,9,4,Jun-Aug,Families,YES,YES,NO,YES,YES,YES,The Westin las Vegas Hotel Casino & Spa,4,826,Asia,6,July,Monday
493,USA,9,8,1,5,Jun-Aug,Couples,YES,YES,NO,YES,YES,YES,The Westin las Vegas Hotel Casino & Spa,4,826,North America,6,July,Monday
494,USA,23,21,22,3,Jun-Aug,Families,YES,YES,NO,YES,YES,YES,The Westin las Vegas Hotel Casino & Spa,4,826,North America,7,August,Wednesday
495,USA,21,6,3,4,Jun-Aug,Couples,YES,YES,NO,YES,YES,YES,The Westin las Vegas Hotel Casino & Spa,4,826,North America,5,August,Tuesday
496,USA,30,27,19,5,Sep-Nov,Solo,YES,YES,NO,YES,YES,YES,The Westin las Vegas Hotel Casino & Spa,4,826,North America,6,September,Friday
497,USA,63,16,59,3,Sep-Nov,Couples,YES,YES,NO,YES,YES,YES,The Westin las Vegas Hotel Casino & Spa,4,826,North America,11,September,Wednesday
498,UK,35,3,25,5,Sep-Nov,Couples,YES,YES,NO,YES,YES,YES,The Westin las Vegas Hotel Casino & Spa,4,826,Europe,1,October,Monday
499,UK,15,4,8,5,Sep-Nov,Couples,YES,YES,NO,YES,YES,YES,The Westin las Vegas Hotel Casino & Spa,4,826,Europe,1,October,Sunday
500,Canada,50,13,29,4,Sep-Nov,Couples,YES,YES,NO,YES,YES,YES,The Westin las Vegas Hotel Casino & Spa,4,826,North America,8,November,Thursday
501,USA,154,23,31,4,Sep-Nov,Friends,YES,YES,NO,YES,YES,YES,The Westin las Vegas Hotel Casino & Spa,4,826,North America,4,November,Thursday
502,USA,9,6,5,2,Dec-Feb,Families,YES,YES,NO,YES,YES,YES,The Westin las Vegas Hotel Casino & Spa,4,826,North America,9,December,Wednesday
503,USA,20,19,112,4,Dec-Feb,Families,YES,YES,NO,YES,YES,YES,The Westin las Vegas Hotel Casino & Spa,4,826,North America,5,December,Tuesday

In [16]:


df['Casino']=df['Casino'].apply(lambda x : yesNo(x))
df['Gym']=df['Gym'].apply(lambda x : yesNo(x))
df['Pool']=df['Pool'].apply(lambda x : yesNo(x))
df['Tennis court']=df['Tennis court'].apply(lambda x : yesNo(x))
df['Casino']=df['Casino'].apply(lambda x : yesNo(x))
df['Free internet']=df['Free internet'].apply(lambda x : yesNo(x))
df['Spa']=df['Spa'].apply(lambda x : yesNo(x))




cols2 = ['Period of stay', 'Hotel name', 'User country',
         'Traveler type', 'User continent', 'Review month', 'Review weekday']

for y in cols2:
    df[y]=df[y].apply(lambda x: toOrd(x))

In [17]:
df

,User country,Nr. reviews,Nr. hotel reviews,Helpful votes,Score,Period of stay,Traveler type,Pool,Gym,Tennis court,Spa,Casino,Free internet,Hotel name,Hotel stars,Nr. rooms,User continent,Member years,Review month,Review weekday
0,233,11,4,13,5,582,715,0,1,0,0,0,1,3367,3,3773,1245,9,730,852
1,233,119,21,75,3,582,844,0,1,0,0,0,1,3367,3,3773,1245,3,730,607
2,233,36,9,25,5,628,810,0,1,0,0,0,1,3367,3,3773,1245,2,832,845
3,160,14,7,14,4,628,715,0,1,0,0,0,1,3367,3,3773,624,6,832,607
4,568,5,5,2,4,628,413,0,1,0,0,0,1,3367,3,3773,1245,7,491,735
5,568,31,8,27,3,628,731,0,1,0,0,0,1,3367,3,3773,1245,2,491,735
6,160,45,12,46,4,628,731,0,1,0,0,0,1,3367,3,3773,624,4,504,607
7,233,2,1,4,4,628,810,0,1,0,0,0,1,3367,3,3773,1245,0,504,735
8,485,24,3,8,4,628,715,0,1,0,0,0,1,3367,3,3773,382,3,295,845
9,568,12,7,11,3,628,810,0,1,0,0,0,1,3367,3,3773,1245,5,295,735
10,233,102,24,58,2,631,810,0,1,0,0,0,1,3367,3,3773,1245,9,402,607
11,934,20,9,24,3,631,715,0,1,0,0,0,1,3367,3,3773,688,4,402,845
12,233,7,6,9,2,631,715,0,1,0,0,0,1,3367,3,3773,1245,1,420,932
13,233,22,5,13,3,631,715,0,1,0,0,0,1,3367,3,3773,1245,1,420,852
14,160,3,3,0,3,631,715,0,1,0,0,0,1,3367,3,3773,624,1,633,628
15,936,146,17,33,4,631,810,0,1,0,0,0,1,3367,3,3773,688,2,633,845
16,568,8,8,9,1,648,810,0,1,0,0,0,1,3367,3,3773,1245,4,935,932
17,233,9,3,1,4,648,810,0,1,0,0,0,1,3367,3,3773,1245,2,935,845
18,568,41,9,19,3,648,731,0,1,0,0,0,1,3367,3,3773,1245,2,718,735
19,233,8,7,26,2,648,731,0,1,0,0,0,1,3367,3,3773,1245,10,718,616
20,160,10,5,2,4,648,731,0,1,0,0,0,1,3367,3,3773,624,7,830,845
21,936,4,3,3,1,648,731,0,1,0,0,0,1,3367,3,3773,688,3,830,616
22,160,18,7,19,4,582,810,0,1,0,0,0,1,3367,3,3773,624,0,791,845
23,233,4,4,3,2,582,731,0,1,0,0,0,1,3367,3,3773,1245,5,791,628
24,703,29,11,15,4,582,731,1,1,0,1,0,1,2174,3,3981,624,3,730,616
25,233,114,42,52,4,582,844,1,1,0,1,0,1,2174,3,3981,1245,11,730,845
26,568,30,12,17,5,582,731,1,1,0,1,0,1,2174,3,3981,1245,8,832,607
27,160,87,18,36,3,582,844,1,1,0,1,0,1,2174,3,3981,624,3,832,852
28,233,26,10,28,5,628,413,1,1,0,1,0,1,2174,3,3981,1245,1,491,932
29,703,8,7,9,5,628,731,1,1,0,1,0,1,2174,3,3981,624,8,491,932
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
474,568,18,3,10,2,648,731,1,1,0,1,0,1,1365,4,2916,1245,2,718,616
475,233,6,4,6,5,648,731,1,1,0,1,0,1,1365,4,2916,1245,0,718,845
476,233,48,8,25,4,648,731,1,1,0,1,0,1,1365,4,2916,1245,6,830,616
477,233,24,3,5,5,648,731,1,1,0,1,0,1,1365,4,2916,1245,0,830,628
478,568,123,26,63,5,582,731,1,1,0,1,0,1,1365,4,2916,1245,4,791,845
479,233,24,7,6,4,582,715,1,1,0,1,0,1,1365,4,2916,1245,1,791,852
480,568,20,13,17,4,582,731,1,1,0,1,0,1,3412,4,826,1245,4,730,616
481,233,15,3,4,3,582,810,1,1,0,1,0,1,3412,4,826,1245,7,730,735
482,515,189,72,129,4,582,413,1,1,0,1,0,1,3412,4,826,624,3,832,607
483,233,25,19,27,3,582,731,1,1,0,1,0,1,3412,4,826,1245,8,832,616
484,233,33,11,12,5,628,844,1,1,0,1,0,1,3412,4,826,1245,4,491,932
485,233,14,7,13,5,628,715,1,1,0,1,0,1,3412,4,826,1245,4,491,852
486,233,38,22,47,4,628,844,1,1,0,1,0,1,3412,4,826,1245,4,504,616
487,521,169,43,85,4,628,413,1,1,0,1,0,1,3412,4,826,582,12,504,628
488,233,20,17,21,3,628,715,1,1,0,1,0,1,3412,4,826,1245,4,295,628
489,233,17,10,18,4,628,731,1,1,0,1,0,1,3412,4,826,1245,3,295,735
490,233,96,47,161,4,631,413,1,1,0,1,0,1,3412,4,826,1245,11,402,616
491,233,38,13,11,3,631,844,1,1,0,1,0,1,3412,4,826,1245,5,402,628
492,485,12,11,9,4,631,810,1,1,0,1,0,1,3412,4,826,382,6,420,616
493,233,9,8,1,5,631,731,1,1,0,1,0,1,3412,4,826,1245,6,420,616
494,233,23,21,22,3,631,810,1,1,0,1,0,1,3412,4,826,1245,7,633,932
495,233,21,6,3,4,631,731,1,1,0,1,0,1,3412,4,826,1245,5,633,735
496,233,30,27,19,5,648,413,1,1,0,1,0,1,3412,4,826,1245,6,935,607
497,233,63,16,59,3,648,731,1,1,0,1,0,1,3412,4,826,1245,11,935,932
498,160,35,3,25,5,648,731,1,1,0,1,0,1,3412,4,826,624,1,718,616
499,160,15,4,8,5,648,731,1,1,0,1,0,1,3412,4,826,624,1,718,628
500,568,50,13,29,4,648,731,1,1,0,1,0,1,3412,4,826,1245,8,830,852
501,233,154,23,31,4,648,715,1,1,0,1,0,1,3412,4,826,1245,4,830,852
502,233,9,6,5,2,582,810,1,1,0,1,0,1,3412,4,826,1245,9,791,932
503,233,20,19,112,4,582,810,1,1,0,1,0,1,3412,4,826,1245,5,791,735

In [18]:
df.to_csv('tripAdvisorFL.csv')